apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-health-check-api
spec:
  template:
    spec:
      containers:
        - name: veidemann-health-check-api
          env:
            - name: VEIDEMANN_DASHBOARD_URL
              value: http://veidemann-dashboard/veidemann
            - name: CONTROLLER_API_KEY
              value: ABCD-1234
              valueFrom: # unset base
          volumeMounts:
            - mountPath: /versions.json
              subPath: versions.json
              name: veidemann
              readOnly: true
      volumes:
        - name: veidemann
          configMap:
            name: veidemann-health-check-api-env
            items:
              - key: versions.json
                path: versions.json
