kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: veidemann

resources:
  - github.com/nlnwa/veidemann/bases/veidemann-health-check-api

patchesStrategicMerge:
  - deployment_patch.yaml

configMapGenerator:
  - name: veidemann-health-check-api-env
    files:
      - versions.json
