name: Docker

on:
  push:
    tags:
      - v*

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: norsknettarkiv/veidemann-health-check-api
          tag_with_ref: true
          tags: latest
          add_git_labels: true
          build_args: VERSION=${{steps.get_version.outputs.VERSION}}
